//
// Generated by Bluespec Compiler, version 2011.06.D (build 24470, 2011-06-30)
//
// On Tue Aug 30 10:59:12 IST 2011
//
// Method conflict info:
// (none)
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module mkTb(CLK,
	    RST_N);
  input  CLK;
  input  RST_N;

  // register hex
  reg [3 : 0] hex;
  wire [3 : 0] hex$D_IN;
  wire hex$EN;

  // ports of submodule h2s
  wire [6 : 0] h2s$decode;
  wire [3 : 0] h2s$decode_hex, h2s$dispsegment;

  // submodule h2s
  mkh2s h2s(.CLK(CLK),
	    .RST_N(RST_N),
	    .decode_hex(h2s$decode_hex),
	    .decode(h2s$decode),
	    .RDY_decode(),
	    .dispsegment(h2s$dispsegment),
	    .RDY_dispsegment());

  // register hex
  assign hex$D_IN = hex + 4'd1 ;
  assign hex$EN = 1'd1 ;

  // submodule h2s
  assign h2s$decode_hex = hex ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (!RST_N)
      begin
        hex <= `BSV_ASSIGNMENT_DELAY 4'd0;
      end
    else
      begin
        if (hex$EN) hex <= `BSV_ASSIGNMENT_DELAY hex$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    hex = 4'hA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N)
      $display("AnodeSelected: %b\tHex Number: %b\t LED Signals: %b\n",
	       h2s$dispsegment,
	       hex,
	       h2s$decode);
    if (RST_N) if (hex == 4'b1111) $finish(32'd0);
  end
  // synopsys translate_on
endmodule  // mkTb

