//
// Generated by Bluespec Compiler, version 2011.06.D (build 24470, 2011-06-30)
//
// On Tue Aug 30 16:09:59 IST 2011
//
// Method conflict info:
// (none)
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module mkTb(CLK,
	    RST_N);
  input  CLK;
  input  RST_N;

  // register c
  reg [11 : 0] c;
  wire [11 : 0] c$D_IN;
  wire c$EN;

  // ports of submodule disp
  wire [6 : 0] disp$retSegmentData;
  wire [3 : 0] disp$retAnodeSelected;

  // submodule disp
  mkMukhya disp(.CLK(CLK),
		.RST_N(RST_N),
		.retAnodeSelected(disp$retAnodeSelected),
		.RDY_retAnodeSelected(),
		.retSegmentData(disp$retSegmentData),
		.RDY_retSegmentData());

  // register c
  assign c$D_IN = c + 12'd1 ;
  assign c$EN = 1'd1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (!RST_N)
      begin
        c <= `BSV_ASSIGNMENT_DELAY 12'd0;
      end
    else
      begin
        if (c$EN) c <= `BSV_ASSIGNMENT_DELAY c$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    c = 12'hAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N)
      if (c == 12'd0)
	$display("Anode Selected: %b\tLED Data: %b\n",
		 disp$retAnodeSelected,
		 disp$retSegmentData);
  end
  // synopsys translate_on
endmodule  // mkTb

